GET http://localhost:3000/post
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoic2FyYXZhbmFuIiwiaWF0IjoxNzMxOTMyMjg0LCJleHAiOjE3MzE5MzIyOTl9.Q0PKRyB3dwlZQSZi0UmhsSyQWYUfAZpVJ6jdf8OH9fU

###
POST http://localhost:4000/token
Content-Type: application/json

{
    "token":
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoic2FyYXZhbmFuIiwiaWF0IjoxNzMxOTMyMjI0fQ.ujeO9pJ5nhLDsyHu3RsguQ2VLgEUgF5Sv822sl41Zjw"
}

###

POST http://localhost:4000/login 
Content-Type: application/json

{
"username": "saravanan"
}